pip install aiohttp
pip install aiosignal
pip install aiostream
pip install alabaster
pip install annotated-types
pip install anyio
pip install argon2-cffi
pip install argon2-cffi-bindings
pip install arrow
pip install asgiref
pip install asttokens
pip install async-lru
pip install async-timeout
pip install attrs
pip install Babel
pip install beautifulsoup4
pip install bidict
pip install bleach
pip install bs4
pip install build
pip install CacheControl
pip install cachetools
pip install certifi
pip install cffi
pip install charset-normalizer
pip install cleo
pip install click
pip install cloudpickle
pip install colorama
pip install comm
pip install commonmark
pip install configparser
pip install contourpy
pip install crashtest
pip install cryptography
pip install cycler
pip install dataclasses-json
pip install debugpy
pip install decorator
pip install defusedxml
pip install distlib
pip install docutils
pip install dulwich
pip install exceptiongroup
pip install executing
pip install fastapi
pip install fastapi_poe
pip install fastjsonschema
pip install filelock
pip install fonttools
pip install fqdn
pip install frozenlist
pip install fsspec
pip install google-api-core
pip install google-api-python-client
pip install google-auth
pip install google-auth-httplib2
pip install google-auth-oauthlib
pip install googleapis-common-protos
pip install greenlet
pip install grpclib
pip install h11
pip install h2
pip install hpack
pip install html2text
pip install httpcore
pip install httplib2
pip install httpx
pip install httpx-sse
pip install huggingface-hub
pip install hyperframe
pip install idna
pip install imagesize
pip install importlib-metadata
pip install installer
pip install ipykernel
pip install ipython
pip install ipywidgets
pip install isoduration
pip install jaraco.classes
pip install jedi
pip install jeepney
pip install jgtapy
pip install jgtpy
pip install Jinja2
pip install json5
pip install jsonpatch
pip install jsonpointer
pip install jsonschema
pip install jsonschema-specifications
pip install jupyter
pip install jupyter-console
pip install jupyter-events
pip install jupyter-lsp
pip install jupyter_client
pip install jupyter_core
pip install jupyter_server
pip install jupyter_server_terminals
pip install jupyterlab
pip install jupyterlab-pygments
pip install jupyterlab-widgets
pip install jupyterlab_server
pip install keyring
pip install kiwisolver
pip install langchain
pip install langsmith
pip install markdown-it-py
pip install MarkupSafe
pip install marshmallow
pip install matplotlib
pip install matplotlib-inline
pip install mdurl
pip install mistune
pip install modal
pip install more-itertools
pip install mplfinance
pip install msgpack
pip install multidict
pip install mypy-extensions
pip install nbclient
pip install nbconvert
pip install nbformat
pip install nest-asyncio
pip install nh3
pip install notebook
pip install notebook_shim
pip install numpy
pip install oauthlib
pip install openai
pip install overrides
pip install packaging
pip install pandas
pip install pandocfilters
pip install parso
pip install pexpect
pip install Pillow
pip install pkginfo
pip install platformdirs
pip install poetry
pip install poetry-core
pip install poetry-plugin-export
pip install prometheus-client
pip install prompt-toolkit
pip install protobuf
pip install psutil
pip install ptyprocess
pip install pure-eval
pip install pyasn1
pip install pyasn1-modules
pip install pycparser
pip install pydantic
pip install pydantic_core
pip install Pygments
pip install pyparsing
pip install pyperclip
pip install pyproject_hooks
pip install PySocks
pip install python-dateutil
pip install python-dotenv
pip install python-engineio
pip install python-json-logger
pip install python-socketio
pip install pytz
pip install PyYAML
pip install pyzmq
pip install qtconsole
pip install QtPy
pip install rapidfuzz
pip install readme-renderer
pip install referencing
pip install requests
pip install requests-oauthlib
pip install requests-toolbelt
pip install rfc3339-validator
pip install rfc3986
pip install rfc3986-validator
pip install rich
pip install rpds-py
pip install rsa
pip install SecretStorage
pip install Send2Trash
pip install shell-genie
pip install shellingham
pip install sigtools
pip install six
pip install sniffio
pip install snowballstemmer
pip install soupsieve
pip install Sphinx
pip install sphinx-rtd-theme
pip install sphinxcontrib-applehelp
pip install sphinxcontrib-devhelp
pip install sphinxcontrib-htmlhelp
pip install sphinxcontrib-jquery
pip install sphinxcontrib-jsmath
pip install sphinxcontrib-qthelp
pip install sphinxcontrib-serializinghtml
pip install SQLAlchemy
pip install sse-starlette
pip install stack-data
pip install starlette
pip install synchronicity
pip install tabulate
pip install tblib
pip install tenacity
pip install terminado
pip install tinycss2
pip install toml
pip install tomli
pip install tomlkit
pip install tornado
pip install tqdm
pip install traitlets
pip install trove-classifiers
pip install twine
pip install typer
pip install types-certifi
pip install types-python-dateutil
pip install types-toml
pip install typing-inspect
pip install typing_extensions
pip install tzdata
pip install uri-template
pip install uritemplate
pip install urllib3
pip install uvicorn
pip install virtualenv
pip install watchfiles
pip install wcwidth
pip install webcolors
pip install webencodings
pip install websocket-client
pip install widgetsnbextension
pip install yarl
pip install zipp
